install-dependencies.sh
fakeroot is needed to build debian packages on fedora, and it is not
installed by default. It is probably installed by scylla, so in a system
where all packages are being built this will likely be fine, but trying
to build just the tools will lead to failure.
Signed-off-by: Glauber Costa <glauber@scylladb.com>
=> install.sh: install fakeroot

src/java/org/apache/cassandra/tools/nodetool/TableHistograms.java
Instead of throwing an exception, print an error that the keyspace/table
is not found.
See scylladb/scylla-jmx#55
Signed-off-by: Amnon Heiman <amnon@scylladb.com>
=> nodetool/TableHistograms: Print an error when no keyspace/table found

src/java/org/apache/cassandra/tools/NodeProbe.java, src/java/org/apache/cassandra/tools/NodeTool.java, src/java/org/apache/cassandra/tools/nodetool/SSTableInfo.java
Requires seastar patch:
json: Make date formatter use RFC8601/RFC3339 format
Requires scylla patch set "Implement `sstable_info` API command (info on sstables)"
Requires scylla-jmx patch set "sstable_info"
Adds nodetool "sstableinfo" command which simply forwards via JMX to scylla, and presents and formats the resulting tabular data. 
Note this patch set does not add domain object or change the MBean interfaces in tools-java. Instead we use loosly coupled call + composite unpacking.
=> Implement sstable_info nodetool command

dist/common/cassandra.in.sh, tools/bin/cassandra.in.sh
This patch changes how configuration files are copied to the config
directory.
To prevent unneeded large file copy, only yaml files are copied.
Fixes #94
=> cassandra.in.sh: copy only config file to conf

dist/debian/debian/scylla-tools.install, dist/debian/rules.mustache
This series fixes two bugs related to cqlsh installation on debian systems. First, debian doesn't use the standard `site-packages` directory; instead it uses `dist-packages`. Debian python distutils is patched appropriately and installs to the correct directory, but if we build the debian package on Fedora (as we do) the patch is not there, and the files are installed to the wrong directory and not picked up by python.
Second, 87dab77c1e797 ("make sure cqlsh works from the .tar.gz installation") had a mistake in its scylla-tools.install file which caused files which were meant for /usr into /usr/usr. As might be expected, python didn't pick up the files from there either.
Fixes #112 
Fixes #113 
Ref scylladb/scylla#4738
=> Fix cqlsh on debian installations

dist/common/cassandra.in.sh, tools/bin/cassandra.in.sh
fixes #5067
Port for nodetool command was not filled in.
/etc/scylla/cassandra/cassandra-env.sh fills in this port, so
source files need to copy it to temporary directory
=> None of the nodetool commands are working on master AMI

dist/common/cassandra.in.sh, tools/bin/cassandra.in.sh
nodetool doesn't work on deb distros.
scylla-test@amos-ubuntu16:~$ nodetool status
/usr/bin/nodetool: 5: /usr/share/scylla/cassandra/cassandra.in.sh: function: not found
/usr/bin/nodetool: 11: /usr/share/scylla/cassandra/cassandra.in.sh: Syntax error: "}" unexpected
bin/nodetool is interpreted by /bin/sh, it points to bash on CentOS, and points
to dash on deb distros. This patch fixed two incompatible function definition.
Fixes #116
Signed-off-by: Amos Kong <amos@scylladb.com>
/CC @amnonh @syuu1228
=> shell: fix incompatible function definition

dist/common/cassandra.in.sh, tools/bin/cassandra.in.sh
Commit 64ba725727e05898264bf334a39e4ea4b8d6bcdb didn't fix the problem.
Let's change it to a function definition in POSIX shell.
reference:
- https://www.jpsdomain.org/public/2008-JP_bash_vs_dash.pdf
- https://wiki.ubuntu.com/DashAsBinSh#function
/CC @amnonh @penberg
=> shell: refix incompatible function definition

build.xml
Scylla has it's own shard aware driver and it can be
used to optimise connections to the cluster and
minimize cross-shard operations.
Signed-off-by: Piotr Jastrzebski <haaawk@gmail.com>
=> Switch to shard aware driver

pylib/cqlshlib/formatting.py, pylib/cqlshlib/util.py
This fixes some issues in cqlshlib, which make it incompatible with 
Python 3.
We eventually need to make the whole cqlsh work with Python 3 similar to 
what upstream Apache Cassandra is doing:
https://issues.apache.org/jira/browse/CASSANDRA-10190
However, the main motivation for this change is to make sure we can port 
users of cqlshlib (such as scylla-dtest) to Python 3 now.
Tested on both Python 2 and Python 3.
=> Make cqlshlib compatible with Python 3

tools/stress/src/org/apache/cassandra/stress/settings/SettingsSchema.java
COMPACT STORAGE is not used by default when creating a table in Scylla.
It's also not recommended anymore and cassandra supports an alter command to remove it but scylla don't support it yet.
The usage of compact storage have some limitations like adding and dropping columns.
=> stress: Remove "COMPACT STORAGE" from default c-s schema

build.properties.default, build.xml
It seems maven central repository no longer support http, we need to switch to https:
https://support.sonatype.com/hc/en-us/articles/360041287334
Fixes #137
=> maven: switch repository URL to https

pylib/cqlshlib/__init__.py
`DESC TABLE tbl` called on table with cdc (or on alternator table) now prints, respectively, cdc options or `scylla_tags`.
This is based on: https://github.com/scylladb/scylla-enterprise-tools-java/commit/bb8b88394b64d6afe28845c70ce0b9d879b46866
This change accompanies PR scylladb/scylla#5720
Refs scylladb/scylla#5589
=> cqlshlib: added schema extensions for cdc and scylla_tags

dist/redhat/scylla-tools.spec, reloc/build_deb.sh, reloc/build_rpm.sh, scripts/create-relocatable-package.py
To make unified relocatable package easily, we may want to merge tarballs to single tarball like this:
zcat .tar.gz | gzip -c > scylla-unified.tar.xz
But it's not possible with current relocatable package format, since there are multiple files conflicts, install.sh, SCYLLA--FILE, dist/, README.md, etc..
To support this, we need to archive everything in the directory when building relocatable package.
See: scylladb/scylla#6315
=> reloc-pkg: move all files under project name directory

dist/redhat/build_rpm.sh
Those utilities aren't used for building the rpm, and risk failing
the build on network access.
Fixes #161.
=> dist: redhat: build_rpm: don't install git, wget, yum-utils during build

src/java/org/apache/cassandra/tools/SSTableMetadataViewer.java
when sstablemetadata was invoked with ka/la it printed some
fields that has no meaning for these format, in addition the
values didn't make sense either. Both of those things confused
users that couldn't understand the strange values.
This commit does two things:
1. If fixes the specific problem mentioned in the preface.
2. If future proofs the code in a way that will force the next
developer that adds support for new sstable format to revisit
the printing code and decide which fields are to be printed for this
format.
Fixes #149
=> sstablemetadata: Output only fields relevant to the sstable format

dist/debian/build_deb.sh
Same as scylladb/scylla#6752,
we currently does not able to apply version number fixup for .orig.tar.gz file,
even we applied correct fixup on debian/changelog, becuase it just reading
SCYLLA-VERSION-FILE.
We should parse debian/{changelog,control} instead.
=> dist/debian: apply generated package version for .orig.tar.gz file

reloc/build_deb.sh
Commit 40a65fbd63 ("reloc: Add "--builddir" option to
build_{rpm,deb}.sh") added extra whitespace in the "mv" command of
build_deb.sh. Let remove it to fix a build error.
Fixes #186
=> reloc/build_deb.sh: Fix extra whitespace in"mv" command path

NOTICE.txt, src/java/org/apache/cassandra/tools/NodeProbe.java
Table histagrams uses sampling to calculate the histogram.
There could be a potential problem when querying the JMX multiple times,
the values can potentiallay change so drastically that the histogram
values will not be monotonic.
This patch changes NodeProbe implementation, instead of querying each of
the quantile values from the JMX seperately, it will do a single request
to get the values and then will calculate the histogram itself using the
same aggregation class: BufferSamples as the jmx does.
Fixes scylladb/scylla#6792
Signed-off-by: Amnon Heiman <amnon@scylladb.com>
=> NodeProbe: get all histogram values in a single call

src/java/com/scylladb/tools/ColumnNamesMapping.java
Fixes #193
Columnnamesmapping replaces the schema fetched from cluster to
handle renaming of columns etc. It forgot to preserve droppedColumns,
where we deal with ignored columns.
=> sstableloader: Preserve droppedColumns in column rename handling

SCYLLA-VERSION-GEN, reloc/build_reloc.sh
Instead of using the baked-in values from SCYLLA-VERSION-GEN,
allow passing an override. This will be used by the supermodule
to have an identical product-version-release (especially release,
which contains the git hash) across all packages.
=> build: support passing product-version-release as a parameter

dist/debian/debian_files_gen.py
shutil.rmtree(ignore_errors=True) was for ignores error when directory not exist,
but it also ignores permission error, so we shouldn't use that.
Run os.path.exists() before shutil.rmtree() instead.
=> dist/debian/debian_files_gen.py: don't ignore permission error on shtil.rmtree()

dist/common/cassandra.in.sh
Otherwise, when using `GossipingPropertyFileSnitch`, nodetool would not find it. On installed scylla this file is typically located in `$SCYLLA_CONF`, next to `scylla.yaml`.
Refs scylladb/scylla#7930
=> cassandra.in.sh: Add path to rack/dc properties file to classpath

src/java/com/scylladb/tools/SSTableToCQL.java
Refs #218
If we have multi-level clustering bounds (+1 column) with ranges,
we cannot use multiple where-clauses. Luckily, late insight (where
was this info 5 years ago?) tells us clustering restrictions are
legal to express as tuple expressions in CQL.
Note that this does not fully fix the above issue, as we still get
borked schema info from java driver due to case sensitive "desc"
comparison.
Note also that this is weakly tested since I cannot figure out
how to get dtest to accept and use sstableloader from a local
tools-java properly.
=> sstableloader: Use compound "where" restrictions for clustering

dist/redhat/scylla-tools.spec
CentOS/RHEL and SLES has differnt package name of opejdk, use common
name of JRE.
Note that using common name of Java package is also useful when user want to
use differnt implementation of JRE for Scylla.
Also, disable AutoReqProv which is mistakenly enabled but required for
cross build rpm.
=> dist/redhat: add support SLES

src/java/org/apache/cassandra/service/StorageServiceMBean.java, src/java/org/apache/cassandra/tools/NodeProbe.java, src/java/org/apache/cassandra/tools/nodetool/TopPartitions.java
This change switches the toppartitions call to address
the generic JMX endpoint introduced in scylladb/scylla-jmx#157
It now makes it possible to query multiple tables
and keyspaces for the top partitions of the whole group.
=> nodetool: Make toppartitions call the generic endpoint

src/java/org/apache/cassandra/service/StorageService.java
Normally we use the implementation found in the jmx repository.
This change adds a dummy implementation to the Cassandra implementation
file to fix build errors.
=> fix: Add dummy implementation of getToppartitions

src/java/org/apache/cassandra/locator/EverywhereStrategy.java
5 years ago a new replication strategy was implemented for Scylla in
https://github.com/scylladb/scylla/commit/cc30956c561f0e4b380823e7930d857c9eb2db72
However the tools were never updated to support it.
Recently a new system keyspace that uses this Everywhere replication
strategy was added to Scylla in
https://github.com/scylladb/scylla/commit/617813ba66733ddcca82ac1155247952e73c59d0
This caused offline_tools_test.TestOfflineTools.sstablelevelreset_test dtests to fail with:
'ColumnFamily not found: keyspace1/standard1' not found in
"org.apache.cassandra.exceptions.ConfigurationException: Unable to find
replication strategy class
'org.apache.cassandra.locator.EverywhereStrategy'\n\tat
org.apache.cassandra.utils.FBUtilities.classForName(FBUtilities.java:504)\n\tat …
=> Add EverywhereStrategy class

src/java/org/apache/cassandra/tools/NodeProbe.java
We check for the existence of the new toppartitions JMX API
using Class.getMethod, but use wrong class for List<String>
in parameter list. This change fixes that.
=> node_probe: toppartitions: Fix wrong class in getMethod

src/java/org/apache/cassandra/service/StorageService.java, src/java/org/apache/cassandra/service/StorageServiceMBean.java, src/java/org/apache/cassandra/tools/NodeProbe.java, src/java/org/apache/cassandra/tools/nodetool/Refresh.java
This information is forwarded through JMX to Scylla, adding an extra
{"load_and_stream", "true"} entry in the POST request to Scylla's HTTP API
at `storage_service/sstables/{keyspace}` endpoint.
More about this feature: scylladb/scylla#7846
Mutually bonded change: scylladb/scylla-jmx#176
Fixes #253
=> nodetool: add `--load-and-stream` option to `refresh`

reloc/build_reloc.sh
next build stage is failing with the following error:
```
23:41:53  [760/2763] cd tools/java && ./reloc/build_reloc.sh --version $(<../../build/SCYLLA-PRODUCT-FILE)-$(<../../build/SCYLLA-VERSION-FILE)-$(<../../build/SCYLLA-RELEASE-FILE) --nodeps
23:41:53  ./reloc/build_reloc.sh: line 70: [: missing `]'
```
looks like there's a missing space before the closing bracket (related to changes done in https://github.com/scylladb/scylla-tools-java/commit/a2fe67fd425b29d83f0b9737ea8fa6f6ca095d15)
Fixing
=> reloc/build_reloc.sh: Add missing space

dist/debian/control.template
From Debian 12 and Ubuntu 22.04, we cannot depends to "python" virtual package,
we need to specify "python2" instead.
See scylladb/scylla#9498
=> dist/debian: replace "python (>=2.7)" with "python2"

.build/build-resolver.xml
commit https://github.com/scylladb/scylla-tools-java/commit/2fdf1d27620fe2bce2a3c5989beab40b05fda1e6 from upstream
remove the usage of libraries in ./lib, and fetching them using
`build-resolver.xml`
commit https://github.com/scylladb/scylla-tools-java/commit/8335869e2de98c7167f81a66cef734914e1ec3e4 downloaded newer
version of six to `./lib`, but now need to update the `build-resolver.xml`
with the correct version we need
Fixes: https://github.com/scylladb/scylla-tools-java/issues/87
=> scylla-tools-java: Update "six" library used by cqlsh/python driver

dist/debian/control.template
We have added following conditions on debian/control when we splited
scylla-tools package into scylla-tools and scylla-tools-core:
Package: scylla-tools
Depends: scylla-tools-core (>= 2.0~rc0)
Package: scylla-tools-core
Replaces: scylla-tools (<< 2.0~rc0)
Breaks: scylla-tools (<< 2.0~rc0)
But Scylla < 2.0 is too old, we don't need to support upgrading from
this version anymore, so we can just drop these conditions.
Related: scylladb/scylla-enterprise-tools-java#31
=> dist/debian: drop upgrading from scylla-tools < 2.0

tools/stress/src/org/apache/cassandra/stress/settings/StressSettings.java, tools/stress/src/org/apache/cassandra/stress/util/JavaDriverClient.java
In cases of multiple contact points configued from commandline code was randomly selecting one host and pass that to the cql driver if for some reason that specfic node wasn't available the whole command would fail.
removing this random, and passing all hosts to the driver fix this issue, and the driver code is more then capble of handling a situation of some contact points unreachable
=> cassandra-stress: pass all hosts straight to the driver

pylib/cqlshlib/cql3handling.py
Add `system_distributed_everywhere` keyspace to `SYSTEM_KEYSPACES` list, which marks which keyspaces are recognized as system keyspaces.
This controls for example which keyspaces are not shown when executing `DESC SCHEMA` command in cqlsh. Before this change, `DESC SCHEMA` would print the schema of `system_distributed_everywhere`, which was incorrect as `DESC SCHEMA` is supposed to print only user tables.
Fixes scylladb/scylla-tools-java#318
=> Mark "system_distributed_everywhere" as system keyspace

.build/build-resolver.xml, bin/cqlsh.py, pylib/requirements.txt
This PR adds serverless support for CQLSH. It was previosuly merged, but dtests later discovered a bug in python driver. The bug should be fixed now, so let's merge this again.
@fruch As you had more luck reproducing the issue with dtests than us, could you try and run them with this PR to make sure it works now?
Fixes https://github.com/scylladb/scylla-tools-java/issues/317 (again)
=> Cqlsh serverless v2

build.xml
Since Java 9, javax/xml/bind/DatatypeConverter is no longer available by default, and has to be added as an explicit dependency. This causes the current version of HdrHistogram in cassandra-stress to fail with Java >9.
To fix that, we upgrade HdrHistogram to its current version, which does not have the javax dependency.
Fixes #308
=> Fix cassandra-stress -log hdrfile=... with java 11

install-dependencies.sh
Especially for Java, we really do not need the tens of packages and MBs it adds, just because Java apps can be built and use sound and graphics and whatnot.
=> install-dependencies.sh: do not install weak dependencies

bin/nodetool
Our launcher script (bin/nodetool) currently silently ignores the host parameter and nodetool will use the default value (127.0.0.1). This patch parses and forwards the host parameter to nodetool, so that it is possible to start JMX on other ips than 127.0.0.1.
=> nodetool: parse and forward -h|--host to nodetool

build.xml, src/java/org/apache/cassandra/config/YamlConfigurationLoader.java, tools/stress/src/org/apache/cassandra/stress/StressProfile.java
This PR updates several dependencies in scylla-tools-java: snakeyaml, Jackson, Snappy. Before the change, 
security scanners (such as Trivy) reported that those dependencies were vulnerable to several "HIGH" severity CVEs. Those issues are fixed in newer versions of those libraries and after this PR the security scanner doesn't report any problems related to the updated dependencies.
Fixes #348
Fixes #349
Fixes #350
=> build: update several dependencies

dist/redhat/scylla-tools.spec
in order to tighten the runtime dependencies on different platforms and different components, also, it is better to use a newer and better supported jre, let's use jre-11 in the rpm packaging as well. we build rpm and deb from the same tarball. and we build for both jre-8 and jre-11, so it should be safe to use jre-11 as the dependency on rpm based distros.
=> dist/redhat: s/jre-8-headless/jre-11-headless/

.build/build-resolver.xml
We don't need or support the other platforms.
This removes multi MBs and multiple downloads from Maven, that are not needed during build.
=> resolver: download sigar artifact only for Linux / AMD64

build.xml
This PR updates several dependencies in scylla-tools-java: `Netty` , `Guava` and `Logback`. 
Before the change, security scanners (such as Trivy and the one we have in the docker hub) reported that those dependencies were vulnerable to several "HIGH", "MEDIUM" and "LOW"  severity CVEs. Those issues are fixed in newer versions of those libraries and after this PR the security scanner doesn't report any problems related to the updated dependencies.
Fixes: https://github.com/scylladb/scylla-tools-java/issues/363
Fixes: https://github.com/scylladb/scylla-tools-java/issues/364
Fixes: https://github.com/scylladb/scylla-tools-java/issues/365
=> Update `Netty` , `Guava` and `Logback` dependencies

bin/nodetool-wrapper, dist/debian/debian/scylla-tools.install, dist/redhat/scylla-tools.spec, install.sh
This script is intended as a wrapper for nodetool, first trying to route commands to scylla-nodetool, and if the command is unimplemented, it is routed to the java nodetool. Whether a command is implemented or not is determined by checking the exit-code of scylla-nodetool. An unimplemented command uses a unique exit-code of 100. When this is seen, the command is routed to Java nodetool.
`install.sh` is adjusted to install `nodetool` as `nodetool.java` and `nodetool-wrapper` as `nodetool`. If scylla-nodetool is misbehaving, users can manually fall-back to the legacy nodetool, by invoking `nodetool.java`.
Tests: build both the unified tarball as well as the tools-java one and verified that the script works as intended at the installed location. This will also be checked by Scylla CI.
Refs: …
=> Add nodetool interposer script

install.sh
Same as scylla core repo, we need to run "install -Z" to install files with correct file security context, otherwise we may see SELinux permission error.
Related scylladb/scylladb#8589
=> install.sh: apply correct security context on offline installer

build.xml, install-dependencies.sh, reloc/build_reloc.sh
before this change, we rely on JAVA_HOME to build for java11 target.
but user might set JAVA_HOME to a java-8, in this case the `javac`
from openjdk-8 would fail to compile, because it does not understand
the `--release` option:
```
[javac] Compiling 1 source file to /home/piotrs/src/scylla2/tools/java/build/classes/main/META-INF/versions/11
[javac] javac: invalid flag: --release
[javac] Usage: javac <options> <source files>
[javac] use -help for a list of possible options
```
in this change, we use the JAVA11_HOME environmental variable exposed by
`build_reloc.sh`, so that ant is able to build with the proper java even
if user sets JAVA_HOME to java-8.
=> build.xml: install and use java-11 when building

build.xml
scylla-tools license is missing according to SBOM report .
adding it
Fixes: https://github.com/scylladb/scylla-tools-java/issues/392
=> build.xml: update scylla-tools license
